### ISSUE TITLE
Requiring unknown module "createReactIOSNativeComponentClass"

### ISSUE THREAD

**Issue by ColinUNC** [shevawen/react-native-weather-app#1]
![screen shot 2015-06-24 at 3 41 39 pm](https://cloud.githubusercontent.com/assets/130859/8339724/91e484b8-1a87-11e5-81e8-ab110f031abb.png)

**Comment by shevawen** [comment]
In `node_modules/react-native-svg/svg.js` ,
change `createReactIOSNativeComponentClass` to `createReactNativeComponentClass`

**Comment by ColinUNC** [comment]
@shevawen Thanks. It fixed the issue of  "createReactIOSNativeComponentClass", but got another one.

**Comment by ColinUNC** [comment]
---

Please see this screenshot

![screen shot 2015-06-25 at 12 12 12 pm](https://cloud.githubusercontent.com/assets/130859/8359342/a79807a6-1b33-11e5-91e9-b16f645f0e6a.png)

**Comment by shevawen** [comment]
Change `ReactIOSViewAttributes` to `ReactNativeViewAttributes`, the `react-native-svg` is using an old version of `react-native`.

**Comment by ColinUNC** [comment]
Thanks, It's working now
